package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private BigDecimal idactividad;
     private BigDecimal idcurso;
     private BigDecimal idtipoactividad;
     private String nombre;
     private Date fechainicio;
     private Date fechatermino;
     private BigDecimal cantidadpersona;
     private BigDecimal montorecaudado;
     private Set actividadaporteses = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(BigDecimal idactividad) {
        this.idactividad = idactividad;
    }
    public Actividad(BigDecimal idactividad, BigDecimal idcurso, BigDecimal idtipoactividad, String nombre, Date fechainicio, Date fechatermino, BigDecimal cantidadpersona, BigDecimal montorecaudado, Set actividadaporteses) {
       this.idactividad = idactividad;
       this.idcurso = idcurso;
       this.idtipoactividad = idtipoactividad;
       this.nombre = nombre;
       this.fechainicio = fechainicio;
       this.fechatermino = fechatermino;
       this.cantidadpersona = cantidadpersona;
       this.montorecaudado = montorecaudado;
       this.actividadaporteses = actividadaporteses;
    }
   
    public BigDecimal getIdactividad() {
        return this.idactividad;
    }
    
    public void setIdactividad(BigDecimal idactividad) {
        this.idactividad = idactividad;
    }
    public BigDecimal getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(BigDecimal idcurso) {
        this.idcurso = idcurso;
    }
    public BigDecimal getIdtipoactividad() {
        return this.idtipoactividad;
    }
    
    public void setIdtipoactividad(BigDecimal idtipoactividad) {
        this.idtipoactividad = idtipoactividad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechatermino() {
        return this.fechatermino;
    }
    
    public void setFechatermino(Date fechatermino) {
        this.fechatermino = fechatermino;
    }
    public BigDecimal getCantidadpersona() {
        return this.cantidadpersona;
    }
    
    public void setCantidadpersona(BigDecimal cantidadpersona) {
        this.cantidadpersona = cantidadpersona;
    }
    public BigDecimal getMontorecaudado() {
        return this.montorecaudado;
    }
    
    public void setMontorecaudado(BigDecimal montorecaudado) {
        this.montorecaudado = montorecaudado;
    }
    public Set getActividadaporteses() {
        return this.actividadaporteses;
    }
    
    public void setActividadaporteses(Set actividadaporteses) {
        this.actividadaporteses = actividadaporteses;
    }




}


