package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private BigDecimal idalumno;
     private Apoderado apoderado;
     private Curso curso;
     private String nombre;
     private String direccion;
     private BigDecimal telefono;
     private String correoelectronico;
     private Set contratos = new HashSet(0);
     private Set polizaseguros = new HashSet(0);
     private Set cuentaalumnos = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(BigDecimal idalumno, Apoderado apoderado, Curso curso, String correoelectronico) {
        this.idalumno = idalumno;
        this.apoderado = apoderado;
        this.curso = curso;
        this.correoelectronico = correoelectronico;
    }
    public Alumno(BigDecimal idalumno, Apoderado apoderado, Curso curso, String nombre, String direccion, BigDecimal telefono, String correoelectronico, Set contratos, Set polizaseguros, Set cuentaalumnos) {
       this.idalumno = idalumno;
       this.apoderado = apoderado;
       this.curso = curso;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correoelectronico = correoelectronico;
       this.contratos = contratos;
       this.polizaseguros = polizaseguros;
       this.cuentaalumnos = cuentaalumnos;
    }
   
    public BigDecimal getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(BigDecimal idalumno) {
        this.idalumno = idalumno;
    }
    public Apoderado getApoderado() {
        return this.apoderado;
    }
    
    public void setApoderado(Apoderado apoderado) {
        this.apoderado = apoderado;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }
    
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }
    public Set getPolizaseguros() {
        return this.polizaseguros;
    }
    
    public void setPolizaseguros(Set polizaseguros) {
        this.polizaseguros = polizaseguros;
    }
    public Set getCuentaalumnos() {
        return this.cuentaalumnos;
    }
    
    public void setCuentaalumnos(Set cuentaalumnos) {
        this.cuentaalumnos = cuentaalumnos;
    }




}


