package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Colaborador generated by hbm2java
 */
public class Colaborador  implements java.io.Serializable {


     private BigDecimal idcolaborador;
     private Cuentausuario cuentausuario;
     private Tipocolaborador tipocolaborador;
     private String nombre;
     private String direccion;
     private BigDecimal telefono;
     private String rut;
     private Set contratos = new HashSet(0);

    public Colaborador() {
    }

	
    public Colaborador(BigDecimal idcolaborador, Cuentausuario cuentausuario, Tipocolaborador tipocolaborador, String nombre, BigDecimal telefono) {
        this.idcolaborador = idcolaborador;
        this.cuentausuario = cuentausuario;
        this.tipocolaborador = tipocolaborador;
        this.nombre = nombre;
        this.telefono = telefono;
    }
    public Colaborador(BigDecimal idcolaborador, Cuentausuario cuentausuario, Tipocolaborador tipocolaborador, String nombre, String direccion, BigDecimal telefono, String rut, Set contratos) {
       this.idcolaborador = idcolaborador;
       this.cuentausuario = cuentausuario;
       this.tipocolaborador = tipocolaborador;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.rut = rut;
       this.contratos = contratos;
    }
   
    public BigDecimal getIdcolaborador() {
        return this.idcolaborador;
    }
    
    public void setIdcolaborador(BigDecimal idcolaborador) {
        this.idcolaborador = idcolaborador;
    }
    public Cuentausuario getCuentausuario() {
        return this.cuentausuario;
    }
    
    public void setCuentausuario(Cuentausuario cuentausuario) {
        this.cuentausuario = cuentausuario;
    }
    public Tipocolaborador getTipocolaborador() {
        return this.tipocolaborador;
    }
    
    public void setTipocolaborador(Tipocolaborador tipocolaborador) {
        this.tipocolaborador = tipocolaborador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


