package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Comuna generated by hbm2java
 */
public class Comuna  implements java.io.Serializable {


     private BigDecimal idcomuna;
     private Region region;
     private String nombre;
     private Set colegios = new HashSet(0);

    public Comuna() {
    }

	
    public Comuna(BigDecimal idcomuna, Region region) {
        this.idcomuna = idcomuna;
        this.region = region;
    }
    public Comuna(BigDecimal idcomuna, Region region, String nombre, Set colegios) {
       this.idcomuna = idcomuna;
       this.region = region;
       this.nombre = nombre;
       this.colegios = colegios;
    }
   
    public BigDecimal getIdcomuna() {
        return this.idcomuna;
    }
    
    public void setIdcomuna(BigDecimal idcomuna) {
        this.idcomuna = idcomuna;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getColegios() {
        return this.colegios;
    }
    
    public void setColegios(Set colegios) {
        this.colegios = colegios;
    }




}


