package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuentaalumno generated by hbm2java
 */
public class Cuentaalumno  implements java.io.Serializable {


     private BigDecimal idcuentaalumnos;
     private Alumno alumno;
     private Tipocuenta tipocuenta;
     private BigDecimal cupototal;
     private BigDecimal cupoutilizado;
     private BigDecimal aporte;
     private Set actividadaporteses = new HashSet(0);
     private Set estadocuentas = new HashSet(0);
     private Set pagos = new HashSet(0);

    public Cuentaalumno() {
    }

	
    public Cuentaalumno(BigDecimal idcuentaalumnos, Alumno alumno, Tipocuenta tipocuenta, BigDecimal aporte) {
        this.idcuentaalumnos = idcuentaalumnos;
        this.alumno = alumno;
        this.tipocuenta = tipocuenta;
        this.aporte = aporte;
    }
    public Cuentaalumno(BigDecimal idcuentaalumnos, Alumno alumno, Tipocuenta tipocuenta, BigDecimal cupototal, BigDecimal cupoutilizado, BigDecimal aporte, Set actividadaporteses, Set estadocuentas, Set pagos) {
       this.idcuentaalumnos = idcuentaalumnos;
       this.alumno = alumno;
       this.tipocuenta = tipocuenta;
       this.cupototal = cupototal;
       this.cupoutilizado = cupoutilizado;
       this.aporte = aporte;
       this.actividadaporteses = actividadaporteses;
       this.estadocuentas = estadocuentas;
       this.pagos = pagos;
    }
   
    public BigDecimal getIdcuentaalumnos() {
        return this.idcuentaalumnos;
    }
    
    public void setIdcuentaalumnos(BigDecimal idcuentaalumnos) {
        this.idcuentaalumnos = idcuentaalumnos;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Tipocuenta getTipocuenta() {
        return this.tipocuenta;
    }
    
    public void setTipocuenta(Tipocuenta tipocuenta) {
        this.tipocuenta = tipocuenta;
    }
    public BigDecimal getCupototal() {
        return this.cupototal;
    }
    
    public void setCupototal(BigDecimal cupototal) {
        this.cupototal = cupototal;
    }
    public BigDecimal getCupoutilizado() {
        return this.cupoutilizado;
    }
    
    public void setCupoutilizado(BigDecimal cupoutilizado) {
        this.cupoutilizado = cupoutilizado;
    }
    public BigDecimal getAporte() {
        return this.aporte;
    }
    
    public void setAporte(BigDecimal aporte) {
        this.aporte = aporte;
    }
    public Set getActividadaporteses() {
        return this.actividadaporteses;
    }
    
    public void setActividadaporteses(Set actividadaporteses) {
        this.actividadaporteses = actividadaporteses;
    }
    public Set getEstadocuentas() {
        return this.estadocuentas;
    }
    
    public void setEstadocuentas(Set estadocuentas) {
        this.estadocuentas = estadocuentas;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


