package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuentausuario generated by hbm2java
 */
public class Cuentausuario  implements java.io.Serializable {


     private BigDecimal idcuentausuario;
     private Perfil perfil;
     private String nombreusuario;
     private Blob contrasena;
     private String apellido;
     private String correoelectronico;
     private Set colaboradors = new HashSet(0);

    public Cuentausuario() {
    }

	
    public Cuentausuario(BigDecimal idcuentausuario, Perfil perfil, String nombreusuario, Blob contrasena) {
        this.idcuentausuario = idcuentausuario;
        this.perfil = perfil;
        this.nombreusuario = nombreusuario;
        this.contrasena = contrasena;
    }
    public Cuentausuario(BigDecimal idcuentausuario, Perfil perfil, String nombreusuario, Blob contrasena, String apellido, String correoelectronico, Set colaboradors) {
       this.idcuentausuario = idcuentausuario;
       this.perfil = perfil;
       this.nombreusuario = nombreusuario;
       this.contrasena = contrasena;
       this.apellido = apellido;
       this.correoelectronico = correoelectronico;
       this.colaboradors = colaboradors;
    }
   
    public BigDecimal getIdcuentausuario() {
        return this.idcuentausuario;
    }
    
    public void setIdcuentausuario(BigDecimal idcuentausuario) {
        this.idcuentausuario = idcuentausuario;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public Blob getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(Blob contrasena) {
        this.contrasena = contrasena;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }
    
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }
    public Set getColaboradors() {
        return this.colaboradors;
    }
    
    public void setColaboradors(Set colaboradors) {
        this.colaboradors = colaboradors;
    }




}


