package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Destino generated by hbm2java
 */
public class Destino  implements java.io.Serializable {


     private BigDecimal iddestino;
     private Pais pais;
     private String nombredestino;
     private Set itinerarios = new HashSet(0);

    public Destino() {
    }

	
    public Destino(BigDecimal iddestino, Pais pais) {
        this.iddestino = iddestino;
        this.pais = pais;
    }
    public Destino(BigDecimal iddestino, Pais pais, String nombredestino, Set itinerarios) {
       this.iddestino = iddestino;
       this.pais = pais;
       this.nombredestino = nombredestino;
       this.itinerarios = itinerarios;
    }
   
    public BigDecimal getIddestino() {
        return this.iddestino;
    }
    
    public void setIddestino(BigDecimal iddestino) {
        this.iddestino = iddestino;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombredestino() {
        return this.nombredestino;
    }
    
    public void setNombredestino(String nombredestino) {
        this.nombredestino = nombredestino;
    }
    public Set getItinerarios() {
        return this.itinerarios;
    }
    
    public void setItinerarios(Set itinerarios) {
        this.itinerarios = itinerarios;
    }




}


