package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Itinerario generated by hbm2java
 */
public class Itinerario  implements java.io.Serializable {


     private ItinerarioId id;
     private Actividadviaje actividadviaje;
     private Contrato contrato;
     private Destino destino;
     private Origen origen;
     private Date fechainicio;
     private Date fechatermino;

    public Itinerario() {
    }

	
    public Itinerario(ItinerarioId id, Actividadviaje actividadviaje, Contrato contrato, Destino destino, Origen origen) {
        this.id = id;
        this.actividadviaje = actividadviaje;
        this.contrato = contrato;
        this.destino = destino;
        this.origen = origen;
    }
    public Itinerario(ItinerarioId id, Actividadviaje actividadviaje, Contrato contrato, Destino destino, Origen origen, Date fechainicio, Date fechatermino) {
       this.id = id;
       this.actividadviaje = actividadviaje;
       this.contrato = contrato;
       this.destino = destino;
       this.origen = origen;
       this.fechainicio = fechainicio;
       this.fechatermino = fechatermino;
    }
   
    public ItinerarioId getId() {
        return this.id;
    }
    
    public void setId(ItinerarioId id) {
        this.id = id;
    }
    public Actividadviaje getActividadviaje() {
        return this.actividadviaje;
    }
    
    public void setActividadviaje(Actividadviaje actividadviaje) {
        this.actividadviaje = actividadviaje;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public Destino getDestino() {
        return this.destino;
    }
    
    public void setDestino(Destino destino) {
        this.destino = destino;
    }
    public Origen getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(Origen origen) {
        this.origen = origen;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechatermino() {
        return this.fechatermino;
    }
    
    public void setFechatermino(Date fechatermino) {
        this.fechatermino = fechatermino;
    }




}


