package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private BigDecimal idpago;
     private Cuentaalumno cuentaalumno;
     private Cuentacurso cuentacurso;
     private Tipopago tipopago;
     private Date fechapago;
     private String detalle;
     private BigDecimal montocancelado;

    public Pago() {
    }

	
    public Pago(BigDecimal idpago, Cuentaalumno cuentaalumno, Cuentacurso cuentacurso, Tipopago tipopago) {
        this.idpago = idpago;
        this.cuentaalumno = cuentaalumno;
        this.cuentacurso = cuentacurso;
        this.tipopago = tipopago;
    }
    public Pago(BigDecimal idpago, Cuentaalumno cuentaalumno, Cuentacurso cuentacurso, Tipopago tipopago, Date fechapago, String detalle, BigDecimal montocancelado) {
       this.idpago = idpago;
       this.cuentaalumno = cuentaalumno;
       this.cuentacurso = cuentacurso;
       this.tipopago = tipopago;
       this.fechapago = fechapago;
       this.detalle = detalle;
       this.montocancelado = montocancelado;
    }
   
    public BigDecimal getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(BigDecimal idpago) {
        this.idpago = idpago;
    }
    public Cuentaalumno getCuentaalumno() {
        return this.cuentaalumno;
    }
    
    public void setCuentaalumno(Cuentaalumno cuentaalumno) {
        this.cuentaalumno = cuentaalumno;
    }
    public Cuentacurso getCuentacurso() {
        return this.cuentacurso;
    }
    
    public void setCuentacurso(Cuentacurso cuentacurso) {
        this.cuentacurso = cuentacurso;
    }
    public Tipopago getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(Tipopago tipopago) {
        this.tipopago = tipopago;
    }
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public BigDecimal getMontocancelado() {
        return this.montocancelado;
    }
    
    public void setMontocancelado(BigDecimal montocancelado) {
        this.montocancelado = montocancelado;
    }




}


