package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private BigDecimal idperfil;
     private String descripcion;
     private String estado;
     private Set cuentausuarios = new HashSet(0);
     private Set permisos = new HashSet(0);
     private Set menus = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(BigDecimal idperfil) {
        this.idperfil = idperfil;
    }
    public Perfil(BigDecimal idperfil, String descripcion, String estado, Set cuentausuarios, Set permisos, Set menus) {
       this.idperfil = idperfil;
       this.descripcion = descripcion;
       this.estado = estado;
       this.cuentausuarios = cuentausuarios;
       this.permisos = permisos;
       this.menus = menus;
    }
   
    public BigDecimal getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(BigDecimal idperfil) {
        this.idperfil = idperfil;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCuentausuarios() {
        return this.cuentausuarios;
    }
    
    public void setCuentausuarios(Set cuentausuarios) {
        this.cuentausuarios = cuentausuarios;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }




}


