package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tiposeguro generated by hbm2java
 */
public class Tiposeguro  implements java.io.Serializable {


     private BigDecimal idtiposeguro;
     private String nombre;
     private String descripcion;
     private Set polizaseguros = new HashSet(0);

    public Tiposeguro() {
    }

	
    public Tiposeguro(BigDecimal idtiposeguro) {
        this.idtiposeguro = idtiposeguro;
    }
    public Tiposeguro(BigDecimal idtiposeguro, String nombre, String descripcion, Set polizaseguros) {
       this.idtiposeguro = idtiposeguro;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.polizaseguros = polizaseguros;
    }
   
    public BigDecimal getIdtiposeguro() {
        return this.idtiposeguro;
    }
    
    public void setIdtiposeguro(BigDecimal idtiposeguro) {
        this.idtiposeguro = idtiposeguro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPolizaseguros() {
        return this.polizaseguros;
    }
    
    public void setPolizaseguros(Set polizaseguros) {
        this.polizaseguros = polizaseguros;
    }




}


