package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipoactividadviaje generated by hbm2java
 */
public class Tipoactividadviaje  implements java.io.Serializable {


     private BigDecimal idtipoactividadviaje;
     private String nombre;
     private String descripcion;
     private Set actividadviajes = new HashSet(0);

    public Tipoactividadviaje() {
    }

	
    public Tipoactividadviaje(BigDecimal idtipoactividadviaje) {
        this.idtipoactividadviaje = idtipoactividadviaje;
    }
    public Tipoactividadviaje(BigDecimal idtipoactividadviaje, String nombre, String descripcion, Set actividadviajes) {
       this.idtipoactividadviaje = idtipoactividadviaje;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.actividadviajes = actividadviajes;
    }
   
    public BigDecimal getIdtipoactividadviaje() {
        return this.idtipoactividadviaje;
    }
    
    public void setIdtipoactividadviaje(BigDecimal idtipoactividadviaje) {
        this.idtipoactividadviaje = idtipoactividadviaje;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getActividadviajes() {
        return this.actividadviajes;
    }
    
    public void setActividadviajes(Set actividadviajes) {
        this.actividadviajes = actividadviajes;
    }




}


