package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipopago generated by hbm2java
 */
public class Tipopago  implements java.io.Serializable {


     private BigDecimal idtipopago;
     private String descripcion;
     private Set pagos = new HashSet(0);

    public Tipopago() {
    }

	
    public Tipopago(BigDecimal idtipopago) {
        this.idtipopago = idtipopago;
    }
    public Tipopago(BigDecimal idtipopago, String descripcion, Set pagos) {
       this.idtipopago = idtipopago;
       this.descripcion = descripcion;
       this.pagos = pagos;
    }
   
    public BigDecimal getIdtipopago() {
        return this.idtipopago;
    }
    
    public void setIdtipopago(BigDecimal idtipopago) {
        this.idtipopago = idtipopago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


