package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tipoactividad generated by hbm2java
 */
public class Tipoactividad  implements java.io.Serializable {


     private BigDecimal idtipoactividad;
     private String nombre;

    public Tipoactividad() {
    }

	
    public Tipoactividad(BigDecimal idtipoactividad) {
        this.idtipoactividad = idtipoactividad;
    }
    public Tipoactividad(BigDecimal idtipoactividad, String nombre) {
       this.idtipoactividad = idtipoactividad;
       this.nombre = nombre;
    }
   
    public BigDecimal getIdtipoactividad() {
        return this.idtipoactividad;
    }
    
    public void setIdtipoactividad(BigDecimal idtipoactividad) {
        this.idtipoactividad = idtipoactividad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


