package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipocolaborador generated by hbm2java
 */
public class Tipocolaborador  implements java.io.Serializable {


     private BigDecimal idtipocolaborador;
     private String descripcion;
     private Set colaboradors = new HashSet(0);

    public Tipocolaborador() {
    }

	
    public Tipocolaborador(BigDecimal idtipocolaborador) {
        this.idtipocolaborador = idtipocolaborador;
    }
    public Tipocolaborador(BigDecimal idtipocolaborador, String descripcion, Set colaboradors) {
       this.idtipocolaborador = idtipocolaborador;
       this.descripcion = descripcion;
       this.colaboradors = colaboradors;
    }
   
    public BigDecimal getIdtipocolaborador() {
        return this.idtipocolaborador;
    }
    
    public void setIdtipocolaborador(BigDecimal idtipocolaborador) {
        this.idtipocolaborador = idtipocolaborador;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getColaboradors() {
        return this.colaboradors;
    }
    
    public void setColaboradors(Set colaboradors) {
        this.colaboradors = colaboradors;
    }




}


