package com.duoc.desktravel.model;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tiposervicio generated by hbm2java
 */
public class Tiposervicio  implements java.io.Serializable {


     private BigDecimal idtiposervicio;
     private String nombre;
     private String descripcion;
     private Set servicios = new HashSet(0);

    public Tiposervicio() {
    }

	
    public Tiposervicio(BigDecimal idtiposervicio) {
        this.idtiposervicio = idtiposervicio;
    }
    public Tiposervicio(BigDecimal idtiposervicio, String nombre, String descripcion, Set servicios) {
       this.idtiposervicio = idtiposervicio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.servicios = servicios;
    }
   
    public BigDecimal getIdtiposervicio() {
        return this.idtiposervicio;
    }
    
    public void setIdtiposervicio(BigDecimal idtiposervicio) {
        this.idtiposervicio = idtiposervicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


