package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Actividadaportes generated by hbm2java
 */
public class Actividadaportes  implements java.io.Serializable {


     private ActividadaportesId id;
     private Actividad actividad;
     private Cuentaalumno cuentaalumno;
     private Date fecha;
     private BigDecimal monto;

    public Actividadaportes() {
    }

	
    public Actividadaportes(ActividadaportesId id, Actividad actividad, Cuentaalumno cuentaalumno) {
        this.id = id;
        this.actividad = actividad;
        this.cuentaalumno = cuentaalumno;
    }
    public Actividadaportes(ActividadaportesId id, Actividad actividad, Cuentaalumno cuentaalumno, Date fecha, BigDecimal monto) {
       this.id = id;
       this.actividad = actividad;
       this.cuentaalumno = cuentaalumno;
       this.fecha = fecha;
       this.monto = monto;
    }
   
    public ActividadaportesId getId() {
        return this.id;
    }
    
    public void setId(ActividadaportesId id) {
        this.id = id;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Cuentaalumno getCuentaalumno() {
        return this.cuentaalumno;
    }
    
    public void setCuentaalumno(Cuentaalumno cuentaalumno) {
        this.cuentaalumno = cuentaalumno;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


