package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Actividadviaje generated by hbm2java
 */
public class Actividadviaje  implements java.io.Serializable {


     private BigDecimal idactividadviaje;
     private String nombre;
     private String descripcion;
     private Date fechainicio;
     private Date fechatermino;
     private BigDecimal tipoactividadviaje;

    public Actividadviaje() {
    }

	
    public Actividadviaje(BigDecimal idactividadviaje, BigDecimal tipoactividadviaje) {
        this.idactividadviaje = idactividadviaje;
        this.tipoactividadviaje = tipoactividadviaje;
    }
    public Actividadviaje(BigDecimal idactividadviaje, String nombre, String descripcion, Date fechainicio, Date fechatermino, BigDecimal tipoactividadviaje) {
       this.idactividadviaje = idactividadviaje;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechainicio = fechainicio;
       this.fechatermino = fechatermino;
       this.tipoactividadviaje = tipoactividadviaje;
    }
   
    public BigDecimal getIdactividadviaje() {
        return this.idactividadviaje;
    }
    
    public void setIdactividadviaje(BigDecimal idactividadviaje) {
        this.idactividadviaje = idactividadviaje;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechatermino() {
        return this.fechatermino;
    }
    
    public void setFechatermino(Date fechatermino) {
        this.fechatermino = fechatermino;
    }
    public BigDecimal getTipoactividadviaje() {
        return this.tipoactividadviaje;
    }
    
    public void setTipoactividadviaje(BigDecimal tipoactividadviaje) {
        this.tipoactividadviaje = tipoactividadviaje;
    }




}


