package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ActividadaportesId generated by hbm2java
 */
public class ActividadaportesId  implements java.io.Serializable {


     private BigDecimal idactividadaportes;
     private BigDecimal idcuentaalumnos;

    public ActividadaportesId() {
    }

    public ActividadaportesId(BigDecimal idactividadaportes, BigDecimal idcuentaalumnos) {
       this.idactividadaportes = idactividadaportes;
       this.idcuentaalumnos = idcuentaalumnos;
    }
   
    public BigDecimal getIdactividadaportes() {
        return this.idactividadaportes;
    }
    
    public void setIdactividadaportes(BigDecimal idactividadaportes) {
        this.idactividadaportes = idactividadaportes;
    }
    public BigDecimal getIdcuentaalumnos() {
        return this.idcuentaalumnos;
    }
    
    public void setIdcuentaalumnos(BigDecimal idcuentaalumnos) {
        this.idcuentaalumnos = idcuentaalumnos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActividadaportesId) ) return false;
		 ActividadaportesId castOther = ( ActividadaportesId ) other; 
         
		 return ( (this.getIdactividadaportes()==castOther.getIdactividadaportes()) || ( this.getIdactividadaportes()!=null && castOther.getIdactividadaportes()!=null && this.getIdactividadaportes().equals(castOther.getIdactividadaportes()) ) )
 && ( (this.getIdcuentaalumnos()==castOther.getIdcuentaalumnos()) || ( this.getIdcuentaalumnos()!=null && castOther.getIdcuentaalumnos()!=null && this.getIdcuentaalumnos().equals(castOther.getIdcuentaalumnos()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdactividadaportes() == null ? 0 : this.getIdactividadaportes().hashCode() );
         result = 37 * result + ( getIdcuentaalumnos() == null ? 0 : this.getIdcuentaalumnos().hashCode() );
         return result;
   }   


}


