package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividadviaje generated by hbm2java
 */
public class Actividadviaje  implements java.io.Serializable {


     private BigDecimal idactividadviaje;
     private Tipoactividadviaje tipoactividadviaje;
     private String nombre;
     private String descripcion;
     private Date fechainicio;
     private Date fechatermino;
     private Set itinerarios = new HashSet(0);

    public Actividadviaje() {
    }

	
    public Actividadviaje(BigDecimal idactividadviaje, Tipoactividadviaje tipoactividadviaje) {
        this.idactividadviaje = idactividadviaje;
        this.tipoactividadviaje = tipoactividadviaje;
    }
    public Actividadviaje(BigDecimal idactividadviaje, Tipoactividadviaje tipoactividadviaje, String nombre, String descripcion, Date fechainicio, Date fechatermino, Set itinerarios) {
       this.idactividadviaje = idactividadviaje;
       this.tipoactividadviaje = tipoactividadviaje;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechainicio = fechainicio;
       this.fechatermino = fechatermino;
       this.itinerarios = itinerarios;
    }
   
    public BigDecimal getIdactividadviaje() {
        return this.idactividadviaje;
    }
    
    public void setIdactividadviaje(BigDecimal idactividadviaje) {
        this.idactividadviaje = idactividadviaje;
    }
    public Tipoactividadviaje getTipoactividadviaje() {
        return this.tipoactividadviaje;
    }
    
    public void setTipoactividadviaje(Tipoactividadviaje tipoactividadviaje) {
        this.tipoactividadviaje = tipoactividadviaje;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechatermino() {
        return this.fechatermino;
    }
    
    public void setFechatermino(Date fechatermino) {
        this.fechatermino = fechatermino;
    }
    public Set getItinerarios() {
        return this.itinerarios;
    }
    
    public void setItinerarios(Set itinerarios) {
        this.itinerarios = itinerarios;
    }




}


