package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private BigDecimal idalumno;
     private String nombre;
     private String direccion;
     private BigDecimal apoderado;
     private BigDecimal telefono;
     private String correoelectronico;
     private BigDecimal curso;

    public Alumno() {
    }

	
    public Alumno(BigDecimal idalumno, BigDecimal apoderado, String correoelectronico, BigDecimal curso) {
        this.idalumno = idalumno;
        this.apoderado = apoderado;
        this.correoelectronico = correoelectronico;
        this.curso = curso;
    }
    public Alumno(BigDecimal idalumno, String nombre, String direccion, BigDecimal apoderado, BigDecimal telefono, String correoelectronico, BigDecimal curso) {
       this.idalumno = idalumno;
       this.nombre = nombre;
       this.direccion = direccion;
       this.apoderado = apoderado;
       this.telefono = telefono;
       this.correoelectronico = correoelectronico;
       this.curso = curso;
    }
   
    public BigDecimal getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(BigDecimal idalumno) {
        this.idalumno = idalumno;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getApoderado() {
        return this.apoderado;
    }
    
    public void setApoderado(BigDecimal apoderado) {
        this.apoderado = apoderado;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }
    
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }
    public BigDecimal getCurso() {
        return this.curso;
    }
    
    public void setCurso(BigDecimal curso) {
        this.curso = curso;
    }




}


