package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Anexos generated by hbm2java
 */
public class Anexos  implements java.io.Serializable {


     private BigDecimal idanexo;
     private String file;
     private BigDecimal contrato;
     private String token;

    public Anexos() {
    }

	
    public Anexos(BigDecimal idanexo, String file, BigDecimal contrato) {
        this.idanexo = idanexo;
        this.file = file;
        this.contrato = contrato;
    }
    public Anexos(BigDecimal idanexo, String file, BigDecimal contrato, String token) {
       this.idanexo = idanexo;
       this.file = file;
       this.contrato = contrato;
       this.token = token;
    }
   
    public BigDecimal getIdanexo() {
        return this.idanexo;
    }
    
    public void setIdanexo(BigDecimal idanexo) {
        this.idanexo = idanexo;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }
    public BigDecimal getContrato() {
        return this.contrato;
    }
    
    public void setContrato(BigDecimal contrato) {
        this.contrato = contrato;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }




}


