package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Aseguradora generated by hbm2java
 */
public class Aseguradora  implements java.io.Serializable {


     private BigDecimal idaseguradora;
     private String nombre;
     private String direccion;
     private BigDecimal telefono;
     private String email;
     private String nombrecontacto;
     private String rut;
     private Set polizaseguros = new HashSet(0);

    public Aseguradora() {
    }

	
    public Aseguradora(BigDecimal idaseguradora) {
        this.idaseguradora = idaseguradora;
    }
    public Aseguradora(BigDecimal idaseguradora, String nombre, String direccion, BigDecimal telefono, String email, String nombrecontacto, String rut, Set polizaseguros) {
       this.idaseguradora = idaseguradora;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.nombrecontacto = nombrecontacto;
       this.rut = rut;
       this.polizaseguros = polizaseguros;
    }
   
    public BigDecimal getIdaseguradora() {
        return this.idaseguradora;
    }
    
    public void setIdaseguradora(BigDecimal idaseguradora) {
        this.idaseguradora = idaseguradora;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombrecontacto() {
        return this.nombrecontacto;
    }
    
    public void setNombrecontacto(String nombrecontacto) {
        this.nombrecontacto = nombrecontacto;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public Set getPolizaseguros() {
        return this.polizaseguros;
    }
    
    public void setPolizaseguros(Set polizaseguros) {
        this.polizaseguros = polizaseguros;
    }




}


