package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Colegio generated by hbm2java
 */
public class Colegio  implements java.io.Serializable {


     private BigDecimal idcolegio;
     private Comuna comuna;
     private String nombre;
     private String direccion;
     private BigDecimal telefono;
     private Set cursos = new HashSet(0);

    public Colegio() {
    }

	
    public Colegio(BigDecimal idcolegio, Comuna comuna) {
        this.idcolegio = idcolegio;
        this.comuna = comuna;
    }
    public Colegio(BigDecimal idcolegio, Comuna comuna, String nombre, String direccion, BigDecimal telefono, Set cursos) {
       this.idcolegio = idcolegio;
       this.comuna = comuna;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.cursos = cursos;
    }
   
    public BigDecimal getIdcolegio() {
        return this.idcolegio;
    }
    
    public void setIdcolegio(BigDecimal idcolegio) {
        this.idcolegio = idcolegio;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


