package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Colegio generated by hbm2java
 */
public class Colegio  implements java.io.Serializable {


     private BigDecimal idcolegio;
     private String nombre;
     private String direccion;
     private BigDecimal telefono;
     private BigDecimal idcomuna;

    public Colegio() {
    }

	
    public Colegio(BigDecimal idcolegio, BigDecimal idcomuna) {
        this.idcolegio = idcolegio;
        this.idcomuna = idcomuna;
    }
    public Colegio(BigDecimal idcolegio, String nombre, String direccion, BigDecimal telefono, BigDecimal idcomuna) {
       this.idcolegio = idcolegio;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.idcomuna = idcomuna;
    }
   
    public BigDecimal getIdcolegio() {
        return this.idcolegio;
    }
    
    public void setIdcolegio(BigDecimal idcolegio) {
        this.idcolegio = idcolegio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public BigDecimal getIdcomuna() {
        return this.idcomuna;
    }
    
    public void setIdcomuna(BigDecimal idcomuna) {
        this.idcomuna = idcomuna;
    }




}


