package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Comuna generated by hbm2java
 */
public class Comuna  implements java.io.Serializable {


     private BigDecimal idcomuna;
     private String nombre;
     private BigDecimal region;

    public Comuna() {
    }

	
    public Comuna(BigDecimal idcomuna, BigDecimal region) {
        this.idcomuna = idcomuna;
        this.region = region;
    }
    public Comuna(BigDecimal idcomuna, String nombre, BigDecimal region) {
       this.idcomuna = idcomuna;
       this.nombre = nombre;
       this.region = region;
    }
   
    public BigDecimal getIdcomuna() {
        return this.idcomuna;
    }
    
    public void setIdcomuna(BigDecimal idcomuna) {
        this.idcomuna = idcomuna;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getRegion() {
        return this.region;
    }
    
    public void setRegion(BigDecimal region) {
        this.region = region;
    }




}


