package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Cuentaalumno generated by hbm2java
 */
public class Cuentaalumno  implements java.io.Serializable {


     private BigDecimal idcuentaalumnos;
     private BigDecimal cupototal;
     private BigDecimal cupoutilizado;
     private BigDecimal tipocuenta;
     private BigDecimal alumno;
     private BigDecimal aporte;
     private BigDecimal saldo;

    public Cuentaalumno() {
    }

	
    public Cuentaalumno(BigDecimal idcuentaalumnos, BigDecimal tipocuenta, BigDecimal alumno, BigDecimal aporte) {
        this.idcuentaalumnos = idcuentaalumnos;
        this.tipocuenta = tipocuenta;
        this.alumno = alumno;
        this.aporte = aporte;
    }
    public Cuentaalumno(BigDecimal idcuentaalumnos, BigDecimal cupototal, BigDecimal cupoutilizado, BigDecimal tipocuenta, BigDecimal alumno, BigDecimal aporte, BigDecimal saldo) {
       this.idcuentaalumnos = idcuentaalumnos;
       this.cupototal = cupototal;
       this.cupoutilizado = cupoutilizado;
       this.tipocuenta = tipocuenta;
       this.alumno = alumno;
       this.aporte = aporte;
       this.saldo = saldo;
    }
   
    public BigDecimal getIdcuentaalumnos() {
        return this.idcuentaalumnos;
    }
    
    public void setIdcuentaalumnos(BigDecimal idcuentaalumnos) {
        this.idcuentaalumnos = idcuentaalumnos;
    }
    public BigDecimal getCupototal() {
        return this.cupototal;
    }
    
    public void setCupototal(BigDecimal cupototal) {
        this.cupototal = cupototal;
    }
    public BigDecimal getCupoutilizado() {
        return this.cupoutilizado;
    }
    
    public void setCupoutilizado(BigDecimal cupoutilizado) {
        this.cupoutilizado = cupoutilizado;
    }
    public BigDecimal getTipocuenta() {
        return this.tipocuenta;
    }
    
    public void setTipocuenta(BigDecimal tipocuenta) {
        this.tipocuenta = tipocuenta;
    }
    public BigDecimal getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(BigDecimal alumno) {
        this.alumno = alumno;
    }
    public BigDecimal getAporte() {
        return this.aporte;
    }
    
    public void setAporte(BigDecimal aporte) {
        this.aporte = aporte;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }




}


