package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuentacurso generated by hbm2java
 */
public class Cuentacurso  implements java.io.Serializable {


     private BigDecimal idcuentacurso;
     private Curso curso;
     private BigDecimal saldo;
     private String nombre;
     private String descripcion;
     private String encargado;
     private Set pagos = new HashSet(0);

    public Cuentacurso() {
    }

	
    public Cuentacurso(BigDecimal idcuentacurso, Curso curso) {
        this.idcuentacurso = idcuentacurso;
        this.curso = curso;
    }
    public Cuentacurso(BigDecimal idcuentacurso, Curso curso, BigDecimal saldo, String nombre, String descripcion, String encargado, Set pagos) {
       this.idcuentacurso = idcuentacurso;
       this.curso = curso;
       this.saldo = saldo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.encargado = encargado;
       this.pagos = pagos;
    }
   
    public BigDecimal getIdcuentacurso() {
        return this.idcuentacurso;
    }
    
    public void setIdcuentacurso(BigDecimal idcuentacurso) {
        this.idcuentacurso = idcuentacurso;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(String encargado) {
        this.encargado = encargado;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


