package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Estadocuenta generated by hbm2java
 */
public class Estadocuenta  implements java.io.Serializable {


     private BigDecimal idestadocuenta;
     private BigDecimal cuentaalumno;
     private String detalle;

    public Estadocuenta() {
    }

	
    public Estadocuenta(BigDecimal idestadocuenta, BigDecimal cuentaalumno) {
        this.idestadocuenta = idestadocuenta;
        this.cuentaalumno = cuentaalumno;
    }
    public Estadocuenta(BigDecimal idestadocuenta, BigDecimal cuentaalumno, String detalle) {
       this.idestadocuenta = idestadocuenta;
       this.cuentaalumno = cuentaalumno;
       this.detalle = detalle;
    }
   
    public BigDecimal getIdestadocuenta() {
        return this.idestadocuenta;
    }
    
    public void setIdestadocuenta(BigDecimal idestadocuenta) {
        this.idestadocuenta = idestadocuenta;
    }
    public BigDecimal getCuentaalumno() {
        return this.cuentaalumno;
    }
    
    public void setCuentaalumno(BigDecimal cuentaalumno) {
        this.cuentaalumno = cuentaalumno;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


