package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Estadocuenta generated by hbm2java
 */
public class Estadocuenta  implements java.io.Serializable {


     private BigDecimal idestadocuenta;
     private Cuentaalumno cuentaalumno;
     private String detalle;
     private Date fecha;

    public Estadocuenta() {
    }

	
    public Estadocuenta(BigDecimal idestadocuenta, Cuentaalumno cuentaalumno) {
        this.idestadocuenta = idestadocuenta;
        this.cuentaalumno = cuentaalumno;
    }
    public Estadocuenta(BigDecimal idestadocuenta, Cuentaalumno cuentaalumno, String detalle, Date fecha) {
       this.idestadocuenta = idestadocuenta;
       this.cuentaalumno = cuentaalumno;
       this.detalle = detalle;
       this.fecha = fecha;
    }
   
    public BigDecimal getIdestadocuenta() {
        return this.idestadocuenta;
    }
    
    public void setIdestadocuenta(BigDecimal idestadocuenta) {
        this.idestadocuenta = idestadocuenta;
    }
    public Cuentaalumno getCuentaalumno() {
        return this.cuentaalumno;
    }
    
    public void setCuentaalumno(Cuentaalumno cuentaalumno) {
        this.cuentaalumno = cuentaalumno;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


