package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ItinerarioId generated by hbm2java
 */
public class ItinerarioId  implements java.io.Serializable {


     private BigDecimal iddestino;
     private BigDecimal idactividadviaje;
     private BigDecimal idorigen;

    public ItinerarioId() {
    }

    public ItinerarioId(BigDecimal iddestino, BigDecimal idactividadviaje, BigDecimal idorigen) {
       this.iddestino = iddestino;
       this.idactividadviaje = idactividadviaje;
       this.idorigen = idorigen;
    }
   
    public BigDecimal getIddestino() {
        return this.iddestino;
    }
    
    public void setIddestino(BigDecimal iddestino) {
        this.iddestino = iddestino;
    }
    public BigDecimal getIdactividadviaje() {
        return this.idactividadviaje;
    }
    
    public void setIdactividadviaje(BigDecimal idactividadviaje) {
        this.idactividadviaje = idactividadviaje;
    }
    public BigDecimal getIdorigen() {
        return this.idorigen;
    }
    
    public void setIdorigen(BigDecimal idorigen) {
        this.idorigen = idorigen;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItinerarioId) ) return false;
		 ItinerarioId castOther = ( ItinerarioId ) other; 
         
		 return ( (this.getIddestino()==castOther.getIddestino()) || ( this.getIddestino()!=null && castOther.getIddestino()!=null && this.getIddestino().equals(castOther.getIddestino()) ) )
 && ( (this.getIdactividadviaje()==castOther.getIdactividadviaje()) || ( this.getIdactividadviaje()!=null && castOther.getIdactividadviaje()!=null && this.getIdactividadviaje().equals(castOther.getIdactividadviaje()) ) )
 && ( (this.getIdorigen()==castOther.getIdorigen()) || ( this.getIdorigen()!=null && castOther.getIdorigen()!=null && this.getIdorigen().equals(castOther.getIdorigen()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIddestino() == null ? 0 : this.getIddestino().hashCode() );
         result = 37 * result + ( getIdactividadviaje() == null ? 0 : this.getIdactividadviaje().hashCode() );
         result = 37 * result + ( getIdorigen() == null ? 0 : this.getIdorigen().hashCode() );
         return result;
   }   


}


