package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ItinerarioId generated by hbm2java
 */
public class ItinerarioId  implements java.io.Serializable {


     private BigDecimal destino;
     private BigDecimal actividadviaje;
     private BigDecimal origen;

    public ItinerarioId() {
    }

    public ItinerarioId(BigDecimal destino, BigDecimal actividadviaje, BigDecimal origen) {
       this.destino = destino;
       this.actividadviaje = actividadviaje;
       this.origen = origen;
    }
   
    public BigDecimal getDestino() {
        return this.destino;
    }
    
    public void setDestino(BigDecimal destino) {
        this.destino = destino;
    }
    public BigDecimal getActividadviaje() {
        return this.actividadviaje;
    }
    
    public void setActividadviaje(BigDecimal actividadviaje) {
        this.actividadviaje = actividadviaje;
    }
    public BigDecimal getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(BigDecimal origen) {
        this.origen = origen;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItinerarioId) ) return false;
		 ItinerarioId castOther = ( ItinerarioId ) other; 
         
		 return ( (this.getDestino()==castOther.getDestino()) || ( this.getDestino()!=null && castOther.getDestino()!=null && this.getDestino().equals(castOther.getDestino()) ) )
 && ( (this.getActividadviaje()==castOther.getActividadviaje()) || ( this.getActividadviaje()!=null && castOther.getActividadviaje()!=null && this.getActividadviaje().equals(castOther.getActividadviaje()) ) )
 && ( (this.getOrigen()==castOther.getOrigen()) || ( this.getOrigen()!=null && castOther.getOrigen()!=null && this.getOrigen().equals(castOther.getOrigen()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDestino() == null ? 0 : this.getDestino().hashCode() );
         result = 37 * result + ( getActividadviaje() == null ? 0 : this.getActividadviaje().hashCode() );
         result = 37 * result + ( getOrigen() == null ? 0 : this.getOrigen().hashCode() );
         return result;
   }   


}


