package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private BigDecimal idmenu;
     private Perfil perfil;
     private String nombremenu;

    public Menu() {
    }

	
    public Menu(BigDecimal idmenu, Perfil perfil) {
        this.idmenu = idmenu;
        this.perfil = perfil;
    }
    public Menu(BigDecimal idmenu, Perfil perfil, String nombremenu) {
       this.idmenu = idmenu;
       this.perfil = perfil;
       this.nombremenu = nombremenu;
    }
   
    public BigDecimal getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(BigDecimal idmenu) {
        this.idmenu = idmenu;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNombremenu() {
        return this.nombremenu;
    }
    
    public void setNombremenu(String nombremenu) {
        this.nombremenu = nombremenu;
    }




}


