package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Origen generated by hbm2java
 */
public class Origen  implements java.io.Serializable {


     private BigDecimal idorigen;
     private Pais pais;
     private String nombreorigen;
     private Set itinerarios = new HashSet(0);

    public Origen() {
    }

	
    public Origen(BigDecimal idorigen, Pais pais) {
        this.idorigen = idorigen;
        this.pais = pais;
    }
    public Origen(BigDecimal idorigen, Pais pais, String nombreorigen, Set itinerarios) {
       this.idorigen = idorigen;
       this.pais = pais;
       this.nombreorigen = nombreorigen;
       this.itinerarios = itinerarios;
    }
   
    public BigDecimal getIdorigen() {
        return this.idorigen;
    }
    
    public void setIdorigen(BigDecimal idorigen) {
        this.idorigen = idorigen;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreorigen() {
        return this.nombreorigen;
    }
    
    public void setNombreorigen(String nombreorigen) {
        this.nombreorigen = nombreorigen;
    }
    public Set getItinerarios() {
        return this.itinerarios;
    }
    
    public void setItinerarios(Set itinerarios) {
        this.itinerarios = itinerarios;
    }




}


