package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private BigDecimal idpais;
     private String nombre;

    public Pais() {
    }

	
    public Pais(BigDecimal idpais) {
        this.idpais = idpais;
    }
    public Pais(BigDecimal idpais, String nombre) {
       this.idpais = idpais;
       this.nombre = nombre;
    }
   
    public BigDecimal getIdpais() {
        return this.idpais;
    }
    
    public void setIdpais(BigDecimal idpais) {
        this.idpais = idpais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


