package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private BigDecimal idperfil;
     private String descripcion;
     private String estado;

    public Perfil() {
    }

	
    public Perfil(BigDecimal idperfil) {
        this.idperfil = idperfil;
    }
    public Perfil(BigDecimal idperfil, String descripcion, String estado) {
       this.idperfil = idperfil;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public BigDecimal getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(BigDecimal idperfil) {
        this.idperfil = idperfil;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


