package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private BigDecimal idpermiso;
     private Perfil perfil;
     private String nombre;
     private String descripcion;

    public Permiso() {
    }

	
    public Permiso(BigDecimal idpermiso, Perfil perfil) {
        this.idpermiso = idpermiso;
        this.perfil = perfil;
    }
    public Permiso(BigDecimal idpermiso, Perfil perfil, String nombre, String descripcion) {
       this.idpermiso = idpermiso;
       this.perfil = perfil;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public BigDecimal getIdpermiso() {
        return this.idpermiso;
    }
    
    public void setIdpermiso(BigDecimal idpermiso) {
        this.idpermiso = idpermiso;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


