package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private BigDecimal idregion;
     private String nombre;
     private BigDecimal pais;

    public Region() {
    }

    public Region(BigDecimal idregion, String nombre, BigDecimal pais) {
       this.idregion = idregion;
       this.nombre = nombre;
       this.pais = pais;
    }
   
    public BigDecimal getIdregion() {
        return this.idregion;
    }
    
    public void setIdregion(BigDecimal idregion) {
        this.idregion = idregion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPais() {
        return this.pais;
    }
    
    public void setPais(BigDecimal pais) {
        this.pais = pais;
    }




}


