package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipocuenta generated by hbm2java
 */
public class Tipocuenta  implements java.io.Serializable {


     private BigDecimal idtipocuenta;
     private String nombre;
     private Set cuentaalumnos = new HashSet(0);

    public Tipocuenta() {
    }

	
    public Tipocuenta(BigDecimal idtipocuenta) {
        this.idtipocuenta = idtipocuenta;
    }
    public Tipocuenta(BigDecimal idtipocuenta, String nombre, Set cuentaalumnos) {
       this.idtipocuenta = idtipocuenta;
       this.nombre = nombre;
       this.cuentaalumnos = cuentaalumnos;
    }
   
    public BigDecimal getIdtipocuenta() {
        return this.idtipocuenta;
    }
    
    public void setIdtipocuenta(BigDecimal idtipocuenta) {
        this.idtipocuenta = idtipocuenta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCuentaalumnos() {
        return this.cuentaalumnos;
    }
    
    public void setCuentaalumnos(Set cuentaalumnos) {
        this.cuentaalumnos = cuentaalumnos;
    }




}


