package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tipocontrato generated by hbm2java
 */
public class Tipocontrato  implements java.io.Serializable {


     private BigDecimal idtipocontrato;
     private String nombre;

    public Tipocontrato() {
    }

    public Tipocontrato(BigDecimal idtipocontrato, String nombre) {
       this.idtipocontrato = idtipocontrato;
       this.nombre = nombre;
    }
   
    public BigDecimal getIdtipocontrato() {
        return this.idtipocontrato;
    }
    
    public void setIdtipocontrato(BigDecimal idtipocontrato) {
        this.idtipocontrato = idtipocontrato;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


