package com.duoc.desktravel.entity;
// Generated 15-10-2017 19:02:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipocontrato generated by hbm2java
 */
public class Tipocontrato  implements java.io.Serializable {


     private BigDecimal idtipocontrato;
     private String nombre;
     private Set contratos = new HashSet(0);

    public Tipocontrato() {
    }

	
    public Tipocontrato(BigDecimal idtipocontrato, String nombre) {
        this.idtipocontrato = idtipocontrato;
        this.nombre = nombre;
    }
    public Tipocontrato(BigDecimal idtipocontrato, String nombre, Set contratos) {
       this.idtipocontrato = idtipocontrato;
       this.nombre = nombre;
       this.contratos = contratos;
    }
   
    public BigDecimal getIdtipocontrato() {
        return this.idtipocontrato;
    }
    
    public void setIdtipocontrato(BigDecimal idtipocontrato) {
        this.idtipocontrato = idtipocontrato;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


