package com.duoc.desktravel.entity;
// Generated 09-10-2017 18:36:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tiposervicio generated by hbm2java
 */
public class Tiposervicio  implements java.io.Serializable {


     private BigDecimal idtiposervicio;
     private String nombre;
     private String descripcion;

    public Tiposervicio() {
    }

	
    public Tiposervicio(BigDecimal idtiposervicio) {
        this.idtiposervicio = idtiposervicio;
    }
    public Tiposervicio(BigDecimal idtiposervicio, String nombre, String descripcion) {
       this.idtiposervicio = idtiposervicio;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public BigDecimal getIdtiposervicio() {
        return this.idtiposervicio;
    }
    
    public void setIdtiposervicio(BigDecimal idtiposervicio) {
        this.idtiposervicio = idtiposervicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


