/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duoc.desktravel.view;

import com.duoc.desktravel.model.Colegio;
import com.duoc.desktravel.util.HibernateUtil;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Agustín
 */
public class RegistrarCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarCurso
     */
    public RegistrarCurso() {
        poblarListas();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlColegio = new javax.swing.JPanel();
        lblTituloColegio = new javax.swing.JLabel();
        lblNombreColegio = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblComuna = new javax.swing.JLabel();
        txtDireccionColegio = new javax.swing.JTextField();
        txtNombreColegio = new javax.swing.JTextField();
        txtTelefonoColegio = new javax.swing.JTextField();
        cmbComunaColegio = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnAgregarColegio = new javax.swing.JButton();
        lblSelecColegio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listColegios = new javax.swing.JList<>();
        pnlCurso = new javax.swing.JPanel();
        lblTituloCurso = new javax.swing.JLabel();
        lblNombreCurso = new javax.swing.JLabel();
        lblProfesorCurso = new javax.swing.JLabel();
        txtProfeCurso = new javax.swing.JTextField();
        txtNombreCurso = new javax.swing.JTextField();
        lblSelecCurso = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        listColegios1 = new javax.swing.JList<>();
        btnAgregarCurso = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(852, 456));

        pnlColegio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloColegio.setText("Crear colegio");

        lblNombreColegio.setText("Nombre:");

        lblDireccion.setText("Dirección:");

        lblTelefono.setText("Telefono:");

        lblComuna.setText("Comuna:");

        cmbComunaColegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAgregarColegio.setText("Agregar");

        lblSelecColegio.setText("Seleccionar colegio");

        listColegios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listColegios);

        javax.swing.GroupLayout pnlColegioLayout = new javax.swing.GroupLayout(pnlColegio);
        pnlColegio.setLayout(pnlColegioLayout);
        pnlColegioLayout.setHorizontalGroup(
            pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColegioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlColegioLayout.createSequentialGroup()
                        .addComponent(lblSelecColegio)
                        .addGap(0, 395, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloColegio)
                    .addGroup(pnlColegioLayout.createSequentialGroup()
                        .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreColegio)
                            .addComponent(lblDireccion)
                            .addComponent(lblComuna)
                            .addComponent(lblTelefono))
                        .addGap(23, 23, 23)
                        .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefonoColegio)
                            .addComponent(txtDireccionColegio)
                            .addComponent(txtNombreColegio)
                            .addComponent(cmbComunaColegio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAgregarColegio))
                .addContainerGap())
        );
        pnlColegioLayout.setVerticalGroup(
            pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnlColegioLayout.createSequentialGroup()
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlColegioLayout.createSequentialGroup()
                        .addComponent(lblTituloColegio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreColegio)
                            .addComponent(txtNombreColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccion)
                            .addComponent(txtDireccionColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefonoColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComuna)
                            .addComponent(cmbComunaColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarColegio))
                    .addGroup(pnlColegioLayout.createSequentialGroup()
                        .addComponent(lblSelecColegio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pnlCurso.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloCurso.setText("Crear curso");

        lblNombreCurso.setText("Nombre:");

        lblProfesorCurso.setText("Profesor Jefe:");

        lblSelecCurso.setText("Seleccionar colegio");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        listColegios1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listColegios1);

        btnAgregarCurso.setText("Agregar");

        javax.swing.GroupLayout pnlCursoLayout = new javax.swing.GroupLayout(pnlCurso);
        pnlCurso.setLayout(pnlCursoLayout);
        pnlCursoLayout.setHorizontalGroup(
            pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloCurso)
                    .addGroup(pnlCursoLayout.createSequentialGroup()
                        .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCurso)
                            .addComponent(lblProfesorCurso))
                        .addGap(23, 23, 23)
                        .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProfeCurso)
                            .addComponent(txtNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addComponent(btnAgregarCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblSelecCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2))
        );
        pnlCursoLayout.setVerticalGroup(
            pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursoLayout.createSequentialGroup()
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCurso)
                    .addComponent(lblSelecCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCurso)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesorCurso)
                    .addComponent(txtProfeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnAgregarCurso))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlColegio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlColegio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
         String query = "from Comuna";        
         List res = executeHQLQuery(query);
         //rsltArea.setText(res.toString());
                 

        /*
        // start transaction
        session.beginTransaction();

        // create invitation Object
        Colegio col = new Colegio();
        //col.setComuna();
        col.setDireccion("Nuena imperial 555");
        col.setNombre("Colegio Nuevo");
        col.setTelefono(new BigDecimal(5569));

        // Save the colitation to database
        session.save(col);

        // Commit the transaction
        session.getTransaction().commit();*/
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private List executeHQLQuery(String hql) {
    try {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery(hql);
        List resultList = q.list();
        //displayResult(resultList);
        session.getTransaction().commit();
        return resultList;
    } catch (HibernateException he) {
        List lst = new ArrayList();
        lst.add(he);
        return lst;
    }
}
    
    private void displayResult(List resultList) {
    Vector<String> tableHeaders = new Vector<String>();
    Vector tableData = new Vector();
    tableHeaders.add("Comuna"); 
    tableHeaders.add("Direccion");
    tableHeaders.add("IdColegio");
    tableHeaders.add("Nombre");

    for(Object o : resultList) {
        Colegio colegio = (Colegio)o;
        Vector<Object> oneRow = new Vector<Object>();
        oneRow.add(colegio.getComuna());
        oneRow.add(colegio.getDireccion());
        oneRow.add(colegio.getIdcolegio());
        oneRow.add(colegio.getNombre());
        tableData.add(oneRow);
    }
    //tblResultado.setModel(new DefaultTableModel(tableData, tableHeaders));
} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarColegio;
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cmbComunaColegio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombreColegio;
    private javax.swing.JLabel lblNombreCurso;
    private javax.swing.JLabel lblProfesorCurso;
    private javax.swing.JLabel lblSelecColegio;
    private javax.swing.JLabel lblSelecCurso;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloColegio;
    private javax.swing.JLabel lblTituloCurso;
    private javax.swing.JList<String> listColegios;
    private javax.swing.JList<String> listColegios1;
    private javax.swing.JPanel pnlColegio;
    private javax.swing.JPanel pnlCurso;
    private javax.swing.JTextField txtDireccionColegio;
    private javax.swing.JTextField txtNombreColegio;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JTextField txtProfeCurso;
    private javax.swing.JTextField txtTelefonoColegio;
    // End of variables declaration//GEN-END:variables

    private void poblarListas() {
        
    }
}
